steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "recsys/Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/recs-pipeline:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/recs-pipeline:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/recs-pipeline"

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/recs-pipeline:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/recs-pipeline:latest"

substitutions:
  _REGION: asia-northeast3
  _REPO: seolleyeon-repo

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
