substitutions:
  _IMAGE: asia-northeast3-docker.pkg.dev/seolleyeon-final/seolleyeon-repo/seolleyeon-avatar-worker:manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - lib/ai_recommend_model/avatar_generation/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
